### ISSUE TITLE
Circular import error

### ISSUE THREAD

**Issue by nijel** [adamchainz/django-upgrade#503]
### Python Version

3.11

### Django Version

5.1.1

### Package Version

1.22.0

### Description

When trying to run 1.22.0 it crashes:

```pytb
Traceback (most recent call last):
  File "/home/nijel/weblate/weblate/.venv/bin/django-upgrade", line 5, in <module>
    from django_upgrade.main import main
  File "/home/nijel/weblate/weblate/.venv/lib/python3.11/site-packages/django_upgrade/main.py", line 17, in <module>
    from django_upgrade.ast import ast_parse
  File "/home/nijel/weblate/weblate/.venv/lib/python3.11/site-packages/django_upgrade/ast.py", line 10, in <module>
    from django_upgrade.data import State
  File "/home/nijel/weblate/weblate/.venv/lib/python3.11/site-packages/django_upgrade/data.py", line 206, in <module>
    _import_fixers()
  File "/home/nijel/weblate/weblate/.venv/lib/python3.11/site-packages/django_upgrade/data.py", line 203, in _import_fixers
    __import__(name, fromlist=["_trash"])
  File "/home/nijel/weblate/weblate/.venv/lib/python3.11/site-packages/django_upgrade/fixers/admin_allow_tags.py", line 15, in <module>
    from django_upgrade.ast import ast_start_offset
ImportError: cannot import name 'ast_start_offset' from partially initialized module 'django_upgrade.ast' (most likely due to a circular import) (/home/nijel/weblate/weblate/.venv/lib/python3.11/site-packages/django_upgrade/ast.py)
```

**Comment by adamchainz** [comment]
Thanks for the report. The test suite didn't catch this because of its own imports. I have added a new test and a fix in #505, released in 1.22.1.
