### ISSUE TITLE
cannot import name 'ast_start_offset' from partially initialized module 'django_upgrade.ast' (most likely due to a circular import)

### ISSUE THREAD

**Issue by frague59** [adamchainz/django-upgrade#504]
### Python Version

3.10

### Django Version

4.2.16

### Package Version

latest

### Description

I'using django-upgrade in a pre-commit hook. 

```yaml
  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.22.0
    hooks:
      - id: django-upgrade
        args: [ --target-version, "4.2" ]
```

I've the folowing error while trying to use pre-commit: 

```python
ImportError: cannot import name 'ast_start_offset' from partially initialized module 'django_upgrade.ast' (most likely due to a circular import) (/home/fguerin/.cache/pre-commit/repocbd4oowb/py_env-python3.10/lib/python3.10/site-packages/django_upgrade/ast.py)
Traceback (most recent call last):
  File "/home/fguerin/.cache/pre-commit/repocbd4oowb/py_env-python3.10/bin/django-upgrade", line 5, in <module>
    from django_upgrade.main import main
  File "/home/fguerin/.cache/pre-commit/repocbd4oowb/py_env-python3.10/lib/python3.10/site-packages/django_upgrade/main.py", line 17, in <module>
    from django_upgrade.ast import ast_parse
  File "/home/fguerin/.cache/pre-commit/repocbd4oowb/py_env-python3.10/lib/python3.10/site-packages/django_upgrade/ast.py", line 10, in <module>
    from django_upgrade.data import State
  File "/home/fguerin/.cache/pre-commit/repocbd4oowb/py_env-python3.10/lib/python3.10/site-packages/django_upgrade/data.py", line 206, in <module>
    _import_fixers()
  File "/home/fguerin/.cache/pre-commit/repocbd4oowb/py_env-python3.10/lib/python3.10/site-packages/django_upgrade/data.py", line 203, in _import_fixers
    __import__(name, fromlist=["_trash"])
  File "/home/fguerin/.cache/pre-commit/repocbd4oowb/py_env-python3.10/lib/python3.10/site-packages/django_upgrade/fixers/admin_allow_tags.py", line 15, in <module>
    from django_upgrade.ast import ast_start_offset
ImportError: cannot import name 'ast_start_offset' from partially initialized module 'django_upgrade.ast' (most likely due to a circular import) (/home/fguerin/.cache/pre-commit/repocbd4oowb/py_env-python3.10/lib/python3.10/site-packages/django_upgrade/ast.py)

```

This error is repeating itself many times in the pre-commit output, I've only displayed the last one.

I've tried to delete the `~/.cache/pre-commit/*` directories, to force packages update, with the same result.

Thanks for your help.

**Comment by Ronjea** [comment]
Same is happening to me

**Comment by laroo** [comment]
Same for me; duplicate of #503

**Comment by danjac** [comment]
Same here: downgraded to `1.21.0` for time being.

**Comment by adamchainz** [comment]
Dupe of #503.
